# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eacbab77289ca5a8878303782c926880c9d1c3994868337dfba4119d6c5d505529ad0803f3b1e1a7baad7cead07c61c398f64f9135f4f36a92b3ffa6cc7f9a8c

test:
  secret_key_base: 38c21fd2cf7f49f124ac0c1870f983c354331e04c3e3217cda86332e5abcd584312c81f01505d9bd16d7efe34f9e6a8526a8a726b6420a2fa781fb36023396cd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
